#this service create a new incident for each complaint
class IncidentGenerator
  def self.call(params)
    @complaint = params[:complaint]
    incident = Incident.new(title: 'Autogenerated', 
                severity: @complaint.severity,
                details: @complaint.details)


    return true if incident.save && @complaint.update(incident_id: incident.id)
    false
  end
end
